# Generated by Django 3.0.5 on 2020-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200428_1119'),
        ('carts', '0004_auto_20200427_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='print_variations',
            field=models.ManyToManyField(blank=True, null=True, to='products.PrintPainting'),
        ),
    ]
