# Generated by Django 3.0.5 on 2020-04-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
