# Generated by Django 3.0.5 on 2020-05-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200428_1119'),
        ('carts', '0009_remove_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='print_variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='print_variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.PrintPainting'),
        ),
    ]
