# Generated by Django 3.0.5 on 2020-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200428_1119'),
        ('carts', '0010_auto_20200506_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='print_variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='print_variations',
            field=models.ManyToManyField(blank=True, null=True, to='products.PrintPainting'),
        ),
    ]
