# Generated by Django 3.0.5 on 2020-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200428_1119'),
        ('carts', '0011_auto_20200506_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='print_variations',
            field=models.ManyToManyField(blank=True, to='products.PrintPainting'),
        ),
    ]
