# Generated by Django 3.0.5 on 2020-05-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200501_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Billing', 'Billing')], default='Billing', max_length=100),
        ),
    ]
