# Generated by Django 3.0.5 on 2020-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200501_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Billing', 'Billing')], max_length=100),
        ),
    ]
