# Generated by Django 3.0.5 on 2020-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20200502_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Shipped', 'Shipped'), ('Finished', 'Finished')], default='Started', max_length=100),
        ),
    ]
