# Generated by Django 3.0.5 on 2020-04-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_printpainting_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='printpainting',
            name='productPrint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
