# Generated by Django 3.0.5 on 2020-04-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200424_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prints',
        ),
        migrations.AddField(
            model_name='product',
            name='print_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_one', to='products.PrintPainting'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_two', to='products.PrintPainting'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_three', to='products.PrintPainting'),
        ),
    ]
