# Generated by Django 3.0.5 on 2020-04-24 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200424_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
