# Generated by Django 3.0.5 on 2020-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='printpainting',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
